# Generated by Django 5.1.3 on 2025-01-08 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('mobile', 'Mobile'), ('top wear', 'Top Wear'), ('electronics', 'Electronics'), ('bottom wear', 'Bottom Wear'), ('glasses', 'Glasses')], max_length=20)),
                ('product_image', models.ImageField(upload_to='productimg')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Puducherry', 'Puducherry'), ('Telangana', 'Telangana'), ('Andhra Pradesh', 'Andhra Pradesh'), ('West Bengal', 'West Bengal'), ('Punjab', 'Punjab'), ('Uttarakhand', 'Uttarakhand'), ('Chandigarh', 'Chandigarh'), ('Goa', 'Goa'), ('Tamil Nadu', 'Tamil Nadu'), ('Meghalaya', 'Meghalaya'), ('Delhi', 'Delhi'), ('Maharashtra', 'Maharashtra'), ('Rajasthan', 'Rajasthan'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Sikkim', 'Sikkim'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Assam', 'Assam'), ('Odisha', 'Odisha'), ('Bihar', 'Bihar'), ('Gujrat', 'Gujrat'), ('Nagaland', 'Nagaland'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Adaman & Nicobar Island', 'Adaman & Nicobar Island'), ('chattisgarh', 'chattisgarh'), ('Mizoram', 'Mizoram'), ('Tripura', 'Tripura')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Cancel', 'Cancel'), ('Packed', 'Packed'), ('Accepted', 'Accepted'), ('On the way', 'On the way'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
    ]
