# Generated by Django 5.1.3 on 2025-01-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Odisha', 'Odisha'), ('Nagaland', 'Nagaland'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Adaman & Nicobar Island', 'Adaman & Nicobar Island'), ('chattisgarh', 'chattisgarh'), ('Puducherry', 'Puducherry'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Rajasthan', 'Rajasthan'), ('Mizoram', 'Mizoram'), ('Delhi', 'Delhi'), ('Gujrat', 'Gujrat'), ('Punjab', 'Punjab'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Maharashtra', 'Maharashtra'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Goa', 'Goa'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Chandigarh', 'Chandigarh'), ('Meghalaya', 'Meghalaya'), ('Tripura', 'Tripura'), ('Sikkim', 'Sikkim')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('On the way', 'On the way'), ('Delivered', 'Delivered'), ('Packed', 'Packed'), ('Pending', 'Pending'), ('Cancel', 'Cancel')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('top wear', 'Top Wear'), ('electronics', 'Electronics'), ('mobile', 'Mobile'), ('bottom wear', 'Bottom Wear'), ('glasses', 'Glasses')], max_length=20),
        ),
    ]
