# Generated by Django 5.1.3 on 2025-01-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Gujrat', 'Gujrat'), ('chattisgarh', 'chattisgarh'), ('Delhi', 'Delhi'), ('Nagaland', 'Nagaland'), ('Andhra Pradesh', 'Andhra Pradesh'), ('West Bengal', 'West Bengal'), ('Meghalaya', 'Meghalaya'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Tripura', 'Tripura'), ('Maharashtra', 'Maharashtra'), ('Bihar', 'Bihar'), ('Punjab', 'Punjab'), ('Uttarakhand', 'Uttarakhand'), ('Adaman & Nicobar Island', 'Adaman & Nicobar Island'), ('Telangana', 'Telangana'), ('Puducherry', 'Puducherry'), ('Chandigarh', 'Chandigarh'), ('Tamil Nadu', 'Tamil Nadu'), ('Assam', 'Assam'), ('Odisha', 'Odisha'), ('Goa', 'Goa'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Mizoram', 'Mizoram'), ('Sikkim', 'Sikkim'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Rajasthan', 'Rajasthan')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('Packed', 'Packed'), ('Pending', 'Pending'), ('Cancel', 'Cancel'), ('On the way', 'On the way')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('glasses', 'Glasses'), ('electronics', 'Electronics'), ('bottom wear', 'Bottom Wear'), ('mobile', 'Mobile'), ('top wear', 'Top Wear')], max_length=20),
        ),
    ]
