# Generated by Django 5.1.3 on 2025-01-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Telangana', 'Telangana'), ('Puducherry', 'Puducherry'), ('Goa', 'Goa'), ('Sikkim', 'Sikkim'), ('Rajasthan', 'Rajasthan'), ('Mizoram', 'Mizoram'), ('chattisgarh', 'chattisgarh'), ('Delhi', 'Delhi'), ('Nagaland', 'Nagaland'), ('Meghalaya', 'Meghalaya'), ('Gujrat', 'Gujrat'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Tripura', 'Tripura'), ('Tamil Nadu', 'Tamil Nadu'), ('Punjab', 'Punjab'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Odisha', 'Odisha'), ('West Bengal', 'West Bengal'), ('Uttarakhand', 'Uttarakhand'), ('Chandigarh', 'Chandigarh'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Bihar', 'Bihar'), ('Adaman & Nicobar Island', 'Adaman & Nicobar Island'), ('Assam', 'Assam'), ('Maharashtra', 'Maharashtra')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Packed', 'Packed'), ('On the way', 'On the way'), ('Cancel', 'Cancel'), ('Accepted', 'Accepted')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('glasses', 'Glasses'), ('mobile', 'Mobile'), ('bottom wear', 'Bottom Wear'), ('electronics', 'Electronics'), ('top wear', 'Top Wear')], max_length=20),
        ),
    ]
