# Generated by Django 5.1.3 on 2025-01-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_orderplaced_options_alter_customer_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='app/images/banner/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Odisha', 'Odisha'), ('Tripura', 'Tripura'), ('Delhi', 'Delhi'), ('Assam', 'Assam'), ('Adaman & Nicobar Island', 'Adaman & Nicobar Island'), ('Telangana', 'Telangana'), ('Chandigarh', 'Chandigarh'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Goa', 'Goa'), ('Rajasthan', 'Rajasthan'), ('Gujrat', 'Gujrat'), ('Uttarakhand', 'Uttarakhand'), ('chattisgarh', 'chattisgarh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Bihar', 'Bihar'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Maharashtra', 'Maharashtra'), ('West Bengal', 'West Bengal'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Punjab', 'Punjab'), ('Mizoram', 'Mizoram'), ('Tamil Nadu', 'Tamil Nadu'), ('Nagaland', 'Nagaland'), ('Sikkim', 'Sikkim'), ('Puducherry', 'Puducherry'), ('Meghalaya', 'Meghalaya')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('On the way', 'On the way'), ('Packed', 'Packed')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('top wear', 'Top Wear'), ('bottom wear', 'Bottom Wear'), ('electronics', 'Electronics'), ('glasses', 'Glasses'), ('mobile', 'Mobile')], max_length=20),
        ),
    ]
