# Generated by Django 5.1.3 on 2025-01-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_banner_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('discount_details', models.CharField(default='5% Instant Discount on Axis Bank Credit and Debit Card', max_length=255)),
                ('term_and_condition', models.CharField(default="Term and Condition Applied (For details visit Bank's official Website)", max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Uttarakhand', 'Uttarakhand'), ('Sikkim', 'Sikkim'), ('Rajasthan', 'Rajasthan'), ('West Bengal', 'West Bengal'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Assam', 'Assam'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Mizoram', 'Mizoram'), ('Gujrat', 'Gujrat'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Goa', 'Goa'), ('Delhi', 'Delhi'), ('Odisha', 'Odisha'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Meghalaya', 'Meghalaya'), ('Maharashtra', 'Maharashtra'), ('Nagaland', 'Nagaland'), ('Chandigarh', 'Chandigarh'), ('Tripura', 'Tripura'), ('Punjab', 'Punjab'), ('Bihar', 'Bihar'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Adaman & Nicobar Island', 'Adaman & Nicobar Island'), ('chattisgarh', 'chattisgarh'), ('Puducherry', 'Puducherry')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('On the way', 'On the way'), ('Cancel', 'Cancel'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('glasses', 'Glasses'), ('top wear', 'Top Wear'), ('bottom wear', 'Bottom Wear'), ('electronics', 'Electronics')], max_length=20),
        ),
    ]
