# Generated by Django 5.1.3 on 2025-01-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_livesale_alter_customer_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Goa', 'Goa'), ('Tamil Nadu', 'Tamil Nadu'), ('Nagaland', 'Nagaland'), ('Chandigarh', 'Chandigarh'), ('Telangana', 'Telangana'), ('Bihar', 'Bihar'), ('chattisgarh', 'chattisgarh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Mizoram', 'Mizoram'), ('Adaman & Nicobar Island', 'Adaman & Nicobar Island'), ('Gujrat', 'Gujrat'), ('Maharashtra', 'Maharashtra'), ('Odisha', 'Odisha'), ('Delhi', 'Delhi'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Rajasthan', 'Rajasthan'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Tripura', 'Tripura'), ('West Bengal', 'West Bengal'), ('Punjab', 'Punjab'), ('Puducherry', 'Puducherry'), ('Uttarakhand', 'Uttarakhand'), ('Sikkim', 'Sikkim'), ('Assam', 'Assam'), ('Meghalaya', 'Meghalaya')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Cancel', 'Cancel'), ('Delivered', 'Delivered'), ('On the way', 'On the way'), ('Packed', 'Packed')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('glasses', 'Glasses'), ('electronics', 'Electronics'), ('mobile', 'Mobile'), ('top wear', 'Top Wear'), ('bottom wear', 'Bottom Wear')], max_length=20),
        ),
    ]
