# Generated by Django 5.1.3 on 2025-01-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_banner_is_active_cart_is_active_customer_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Goa', 'Goa'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Adaman & Nicobar Island', 'Adaman & Nicobar Island'), ('Odisha', 'Odisha'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Rajasthan', 'Rajasthan'), ('Puducherry', 'Puducherry'), ('Telangana', 'Telangana'), ('Chandigarh', 'Chandigarh'), ('Sikkim', 'Sikkim'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Mizoram', 'Mizoram'), ('Tamil Nadu', 'Tamil Nadu'), ('West Bengal', 'West Bengal'), ('chattisgarh', 'chattisgarh'), ('Meghalaya', 'Meghalaya'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Tripura', 'Tripura'), ('Nagaland', 'Nagaland'), ('Gujrat', 'Gujrat'), ('Delhi', 'Delhi'), ('Punjab', 'Punjab'), ('Uttarakhand', 'Uttarakhand'), ('Maharashtra', 'Maharashtra')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('On the way', 'On the way'), ('Accepted', 'Accepted'), ('Packed', 'Packed'), ('Delivered', 'Delivered')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('electronics', 'Electronics'), ('glasses', 'Glasses'), ('top wear', 'Top Wear'), ('bottom wear', 'Bottom Wear')], max_length=20),
        ),
    ]
