# Generated by Django 5.1.3 on 2025-01-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Punjab', 'Punjab'), ('chattisgarh', 'chattisgarh'), ('Tamil Nadu', 'Tamil Nadu'), ('West Bengal', 'West Bengal'), ('Rajasthan', 'Rajasthan'), ('Chandigarh', 'Chandigarh'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Nagaland', 'Nagaland'), ('Telangana', 'Telangana'), ('Delhi', 'Delhi'), ('Puducherry', 'Puducherry'), ('Bihar', 'Bihar'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Assam', 'Assam'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Goa', 'Goa'), ('Uttarakhand', 'Uttarakhand'), ('Odisha', 'Odisha'), ('Adaman & Nicobar Island', 'Adaman & Nicobar Island'), ('Gujrat', 'Gujrat'), ('Tripura', 'Tripura'), ('Meghalaya', 'Meghalaya'), ('Sikkim', 'Sikkim'), ('Mizoram', 'Mizoram')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Packed', 'Packed'), ('On the way', 'On the way'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('bottom wear', 'Bottom Wear'), ('glasses', 'Glasses'), ('top wear', 'Top Wear'), ('laptops', 'laptops')], max_length=20),
        ),
    ]
