# Generated by Django 5.1.3 on 2025-01-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Tamil Nadu', 'Tamil Nadu'), ('Odisha', 'Odisha'), ('chattisgarh', 'chattisgarh'), ('Telangana', 'Telangana'), ('Andhra Pradesh', 'Andhra Pradesh'), ('West Bengal', 'West Bengal'), ('Puducherry', 'Puducherry'), ('Mizoram', 'Mizoram'), ('Tripura', 'Tripura'), ('Rajasthan', 'Rajasthan'), ('Meghalaya', 'Meghalaya'), ('Assam', 'Assam'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Chandigarh', 'Chandigarh'), ('Delhi', 'Delhi'), ('Uttarakhand', 'Uttarakhand'), ('Gujrat', 'Gujrat'), ('Goa', 'Goa'), ('Punjab', 'Punjab'), ('Maharashtra', 'Maharashtra'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Nagaland', 'Nagaland'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Bihar', 'Bihar'), ('Adaman & Nicobar Island', 'Adaman & Nicobar Island'), ('Sikkim', 'Sikkim')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('On the way', 'On the way'), ('Accepted', 'Accepted'), ('Packed', 'Packed')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bottom wear', 'Bottom Wear'), ('mobile', 'Mobile'), ('top wear', 'Top Wear'), ('glasses', 'Glasses'), ('laptops', 'laptops')], max_length=20),
        ),
    ]
