# Generated by Django 5.1.3 on 2025-01-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Odisha', 'Odisha'), ('Puducherry', 'Puducherry'), ('Bihar', 'Bihar'), ('Maharashtra', 'Maharashtra'), ('chattisgarh', 'chattisgarh'), ('Chandigarh', 'Chandigarh'), ('West Bengal', 'West Bengal'), ('Tamil Nadu', 'Tamil Nadu'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Tripura', 'Tripura'), ('Uttarakhand', 'Uttarakhand'), ('Punjab', 'Punjab'), ('Telangana', 'Telangana'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Nagaland', 'Nagaland'), ('Rajasthan', 'Rajasthan'), ('Adaman & Nicobar Island', 'Adaman & Nicobar Island'), ('Meghalaya', 'Meghalaya'), ('Assam', 'Assam'), ('Goa', 'Goa'), ('Delhi', 'Delhi'), ('Gujrat', 'Gujrat'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Sikkim', 'Sikkim'), ('Mizoram', 'Mizoram')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Packed', 'Packed'), ('Accepted', 'Accepted'), ('On the way', 'On the way')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('laptop', 'laptop'), ('bottom wear', 'Bottom Wear'), ('glasses', 'Glasses'), ('top wear', 'Top Wear'), ('mobile', 'Mobile')], max_length=20),
        ),
    ]
