# Generated by Django 5.1.3 on 2025-01-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Gujrat', 'Gujrat'), ('Delhi', 'Delhi'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Tripura', 'Tripura'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Rajasthan', 'Rajasthan'), ('West Bengal', 'West Bengal'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Adaman & Nicobar Island', 'Adaman & Nicobar Island'), ('Sikkim', 'Sikkim'), ('Maharashtra', 'Maharashtra'), ('Goa', 'Goa'), ('Meghalaya', 'Meghalaya'), ('Odisha', 'Odisha'), ('Chandigarh', 'Chandigarh'), ('Telangana', 'Telangana'), ('Uttarakhand', 'Uttarakhand'), ('Bihar', 'Bihar'), ('chattisgarh', 'chattisgarh'), ('Punjab', 'Punjab'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Tamil Nadu', 'Tamil Nadu'), ('Puducherry', 'Puducherry'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Cancel', 'Cancel'), ('On the way', 'On the way'), ('Packed', 'Packed'), ('Delivered', 'Delivered')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('bottom wear', 'Bottom Wear'), ('glasses', 'Glasses'), ('laptops', 'laptops'), ('top wear', 'Top Wear')], max_length=20),
        ),
    ]
